Flpz_Project/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Flpz_Project.Data;
using Flpz_Project.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Flpz_Project.Controllers
{
    public class StoreController : Controller
    {
        private readonly ApplicationDbContext _context;

        public StoreController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Profile()
        {
            int? userId = HttpContext.Session.GetInt32("userId");

            return View(userId);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditeUserProfile(int userId)
        {
            Members member = _context.Memberses.FirstOrDefault(u => u.Id == userId);
            ViewBag.Region = new SelectList(_context.Regions, "Id", "RegionName");
            return View(member);
        }

        [HttpGet]
        public IActionResult GetState(int regionId)
        {
            IEnumerable<City> citys = _context.Cities.Where(c => c.RegionId == regionId);
            string xmlstring = "<select name=\"city\" >";
            foreach (var c in citys)
            {
                xmlstring += "<option value = " + c.CityName + " \">" + c.CityName + "</option>";
            }
            xmlstring += "</select>";

            return new ContentResult
            {
                ContentType = "application/xml",
                Content = xmlstring,
                StatusCode = 200
            };
        }
    }
}

Flpz_Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>@ViewData["Title"]</title>
    <link rel="icon" href="~/favicon.ico">
    <link rel="stylesheet" href="~/css/reset.css">
    <link rel="stylesheet" href="~/css/CustomStyle.css" />
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/responsiveslides.css">
    <link rel="stylesheet" href="~/css/bootstrap-responsive.css">
    @*<link rel="stylesheet" href="css/bootstrap.css">*@
    <link href="~/css/selectbox.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
@RenderSection("Body", required: false)
<footer>
    @RenderSection("Footer", required: false)
</footer>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.js"></script>
<script src="~/js/responsiveslides.min.js"></script>
<script src="~/js/jquery.scrollTo-1.3.3.js" type="text/javascript"></script>
<script src="~/js/jquery.serialScroll-1.2.1.js" type="text/javascript"></script>
<script type="text/javascript" src="~/js/jquery.dropdown.js"></script>
<script src="~/js/jquery.selectbox.min.js"></script>
<script src="~/js/jquery.radio.min.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.0/jquery-ui.min.js"></script>
<script type="text/javascript" src="~/js/ui.spinner.js"></script>
<script type="text/javascript" src="~/js/jquery.accordion.js"></script>
<script type="text/javascript" src="~/js/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="~/js/avisa_form_validator.js"></script>
@RenderSection("Script",required: false)
</body>
</html>

Flpz_Project/Views/Shared/_LayoutForStore.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>@ViewData["Title"]</title>
    <link rel="icon" href="~/favicon.ico">
    <link rel="stylesheet" href="~/css/reset.css">
    <link rel="stylesheet" href="~/css/CustomStyle.css" />
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/responsiveslides.css">
    <link rel="stylesheet" href="~/css/bootstrap-responsive.css">
    <link href="~/css/selectbox.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="top-line">
    <div class="container">
        <div class="span2 select-lang-panel">
            <a href="http://www.flptr.com" class="flag-01" title="Turkey">&nbsp;</a>
            <a href="http://www.flpkz.kz" class="flag-02" target="_blank" title="Kazakhstan">&nbsp;</a>
            <a href="http://www.foreverliving.az" class="flag-03" target="_blank" title="Azerbaijan">&nbsp;</a>
            <a href="http://www.foreverliving.kg" class="flag-04" target="_blank" title="Kyrgyzstan">&nbsp;</a>
            <a href="https://www.foreverliving.com/distribNew/Login.do?store=IRQ" class="flag-05" target="_blank" title="Iraq">&nbsp;</a>
        </div>
        <div class="central">Добро пожаловать, <strong>FLP&nbsp;Kyrgyzstan</strong>
        </div>
        <div class="span4">
            <div class="top-navbar">
                <nav>
                    <ul class="nav">
                        <li><a href="/go/?go=main">ГЛАВНАЯ</a></li>
                        <li><a href="/go/?go=eshop">ЗАКАЗ</a></li>
                        <li><a asp-action="Profile" asp-controller="Store">ПРОФИЛЬ</a></li>
                        <li><a href="/go/?go=exit">ВЫХОД</a></li>
                    </ul>
                </nav>
            </div>

            <a href="#" class="show-small-menu"></a>
            <ul class="small-menu">
                <li><a href="/go/?go=main">ГЛАВНАЯ</a></li>
                <li><a href="/go/?go=eshop">ЗАКАЗ</a></li>
                <li><a asp-action="Profile" asp-controller="Store">ПРОФИЛЬ</a></li>
                <li><a href="/go/?go=exit">ВЫХОД</a></li>
            </ul>
        </div>

    </div>
</div>
@RenderSection("Body", required: false)
<footer>
    @RenderSection("Footer", required: false)
</footer>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.js"></script>
<script src="~/js/responsiveslides.min.js"></script>
<script src="~/js/jquery.scrollTo-1.3.3.js" type="text/javascript"></script>
<script src="~/js/jquery.serialScroll-1.2.1.js" type="text/javascript"></script>
<script type="text/javascript" src="~/js/jquery.dropdown.js"></script>
<script src="~/js/jquery.selectbox.min.js"></script>
<script src="~/js/jquery.radio.min.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.0/jquery-ui.min.js"></script>
<script type="text/javascript" src="~/js/ui.spinner.js"></script>
<script type="text/javascript" src="~/js/jquery.accordion.js"></script>
<script type="text/javascript" src="~/js/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="~/js/avisa_form_validator.js"></script>
@RenderSection("Script", required: false)
</body>
</html>